export const ADD_NUMBER = "ADD_NUMBER";
export const SUB_NUMBER = "SUB_NUMBER";
export const INCREASEMENT = "INCREASEMENT"
export const DECREASEMENT = "DECREASEMENT"

export const CHANGE_BANNERS = "CHANGEBANNERS"
export const CHANGE_RECOMMENDS = "CHANGERECOMMENDS"